"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%vj35+iv2v-v3-m-t)%hfe=7&^ftvlfwsjwe+hqjy%44gggp%y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',


]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
db_info = {
    'sqlite': {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    },
    'mysql':  {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': '{{ getenv "dbname" }}',
            'USER': '{{ getenv "dbuser" }}',
            'PASSWORD': '{{ getenv "dbpassword" }}',
            'HOST': '{{ getenv "dbhost" "mysqldb" }}',
            'PORT': '{{ getenv "dbport" "3306" }}',
        }
    }
}


DATABASES = db_info['mysql']


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

STATIC_ROOT = BASE_DIR

ADMIN_MEDIA_PREFIX = "/static/admin/"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )

}

# CELERY STUFF
BROKER_URL = 'redis://{{ getenv "redis_host" "sdcloud_redis" }}:6379'
CELERY_RESULT_BACKEND = 'redis://{{ getenv "redis_host" "sdcloud_redis" }}:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'

# Switch to switch between enterprise and retail
CRITERION_ENV = '{{getenv "environment" "enterprise" }}' # Can take values 'enterprise' or 'retail'

# Variable which tells if the deployment environment is staging, production or
# testing. Defaults to 'testing'.
DEPLOYMENT_ENV = '{{getenv "deployment_env" "testing" }}'

# Company name. Useful only in case of enterprise. Defaults to None.
COMPANY_NAME = None

KEYCLOAK_URL='{{ getenv "keycloak_url" "http://localhost:8080/auth/"}}'
KEYCLOAK_CLIENTID='{{ gentenv "keycloak_clientid" "apibackend" }}'
KEYCLOAK_REALM= '{{ gentenv "keycloak_realm" "Deviare" }}'
KEYCLOAK_CLIENTSECRET= '{{ getenv "keycloak_clientsecret" "c9545c65-9992-44b9-85a2-75ad7e0d0a45" }}'

KEYCLOAK_ADMINUSER= '{{ getenv "keycloak_adminuser" "relamadmin@deviare.co.za" }}'
KEYCLOAK_ADMINPASSWORD= '{{ getenv "keycloak_adminpassword" "longisland" }}'
#KEYCLOAK_USERNAME='test'
#KEYCLOAK_PASSWORD='test123'
#KEYCLOAK_RELAM='Deviare'