# Generated by Django 3.0.2 on 2021-02-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_api', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='billing',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_ip_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='date_completed_gmt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_paid_gmt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='line_items',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='order_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_mail',
            field=models.BooleanField(default=False),
        ),
    ]
