# Generated by Django 3.0.2 on 2021-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_api', '0003_auto_20210209_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproduct',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='image',
            field=models.CharField(default='https://api-staging.deviare.co.za/static/images/default.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='regular_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
