# Generated by Django 3.0.2 on 2021-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='proc_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reference',
            field=models.CharField(max_length=255, null=True, verbose_name='ref'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='recipient',
            field=models.CharField(max_length=255, null=True, verbose_name='Recipient Email'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
