# Generated by Django 3.0.2 on 2020-11-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampost',
            name='feature_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teampost',
            name='qualification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teampost',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
