# Generated by Django 3.0.2 on 2020-11-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201110_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='teampost',
            name='feature_picture',
            field=models.FileField(null=True, upload_to='team_posts/featured/'),
        ),
        migrations.RemoveField(
            model_name='teampost',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teampost',
            name='skills',
        ),
        migrations.AddField(
            model_name='teampost',
            name='qualification',
            field=models.ManyToManyField(related_name='team_post', to='services.Qualification'),
        ),
        migrations.AddField(
            model_name='teampost',
            name='skills',
            field=models.ManyToManyField(related_name='team_post', to='services.Skill'),
        ),
    ]
