# Generated by Django 3.0.6 on 2020-05-07 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
            options={"db_table": "User"},
        )
    ]
