# Generated by Django 3.0.6 on 2020-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user", name="last_login", field=models.DateField(null=True)
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
