# Generated by Django 3.0.6 on 2020-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0005_usersettings")]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="validated",
            field=models.BooleanField(default=False),
        )
    ]
