# Generated by Django 3.0.6 on 2020-06-01 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0007_auto_20200529_1038"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentLicense",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="AssessmentLicenseUser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_license_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.AssessmentLicense",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CourseLicenseUser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DeploymentLicense",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DeploymentLicenseUser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployment_license_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.DeploymentLicense",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ExperimentLicense",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ExperimentLicenseUser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experiment_license_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.ExperimentLicense",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.RenameField(
            model_name="assessment", old_name="_id", new_name="uuid"
        ),
        migrations.RenameField(model_name="company", old_name="_id", new_name="uuid"),
        migrations.RenameField(model_name="course", old_name="_id", new_name="uuid"),
        migrations.RenameField(
            model_name="courselicense", old_name="course", new_name="course_id"
        ),
        migrations.RenameField(
            model_name="courselicense", old_name="project", new_name="project_id"
        ),
        migrations.RenameField(
            model_name="courselicense", old_name="_id", new_name="uuid"
        ),
        migrations.RenameField(
            model_name="deployment", old_name="_id", new_name="uuid"
        ),
        migrations.RenameField(
            model_name="experiment", old_name="_id", new_name="uuid"
        ),
        migrations.RenameField(
            model_name="project", old_name="company", new_name="company_id"
        ),
        migrations.RenameField(
            model_name="project", old_name="admin", new_name="user_id"
        ),
        migrations.RenameField(model_name="project", old_name="_id", new_name="uuid"),
        migrations.RenameField(
            model_name="usersettings", old_name="_id", new_name="uuid"
        ),
        migrations.RemoveField(model_name="usersettings", name="is_active"),
        migrations.RemoveField(model_name="usersettings", name="is_staff"),
        migrations.RemoveField(model_name="usersettings", name="is_superuser"),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(name="CourseUser"),
        migrations.AddField(
            model_name="experimentlicense",
            name="experiment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.Experiment"
            ),
        ),
        migrations.AddField(
            model_name="experimentlicense",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.Project"
            ),
        ),
        migrations.AddField(
            model_name="deploymentlicense",
            name="deployment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.Deployment"
            ),
        ),
        migrations.AddField(
            model_name="deploymentlicense",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.Project"
            ),
        ),
        migrations.AddField(
            model_name="courselicenseuser",
            name="course_license_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.CourseLicense"
            ),
        ),
        migrations.AddField(
            model_name="courselicenseuser",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assessmentlicense",
            name="assessment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.Assessment"
            ),
        ),
        migrations.AddField(
            model_name="assessmentlicense",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.Project"
            ),
        ),
    ]
