# Generated by Django 3.0.6 on 2020-06-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0008_auto_20200601_1805")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
