# Generated by Django 3.0.6 on 2020-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0009_auto_20200602_1217")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        )
    ]
