# Generated by Django 3.0.6 on 2020-06-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0010_auto_20200608_1546")]

    operations = [
        migrations.RemoveField(model_name="project", name="user_id"),
        migrations.AddField(
            model_name="project",
            name="company_admin_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocated_admin",
                to="main.UserSettings",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="startDate",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="superadmin_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to="main.UserSettings",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Complete", "Complete")],
                default="Open",
                max_length=20,
            ),
        ),
    ]
