# Generated by Django 3.0.6 on 2020-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0013_auto_20200618_0100")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(default="Deviare Courses", max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="course_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
