# Generated by Django 3.0.6 on 2020-07-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0016_auto_20200625_1035")]

    operations = [
        migrations.AlterField(
            model_name="company", name="email", field=models.EmailField(max_length=150)
        )
    ]
