# Generated by Django 3.0.6 on 2020-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0017_auto_20200713_1541")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact_no",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
