# Generated by Django 3.0.6 on 2020-08-07 22:58

from django.db import migrations, models
import django.db.models.deletion
import main.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200713_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('config', main.fields.SimpleJSONField(blank=True, default='', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='main.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
