# Generated by Django 3.0.6 on 2020-08-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0018_auto_20200730_1531")]

    operations = [
        migrations.AddField(
            model_name="courselicenseuser",
            name="course_completion",
            field=models.IntegerField(null=True),
        )
    ]
