# Generated by Django 3.0.6 on 2020-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0019_courselicenseuser_course_completion")]

    operations = [
        migrations.AlterField(
            model_name="courselicenseuser",
            name="course_completion",
            field=models.FloatField(null=True),
        )
    ]
