# Generated by Django 3.0.6 on 2020-08-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0020_auto_20200810_1853")]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="customers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="customers", to="main.Company"
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="companyID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="main.Company",
            ),
        ),
    ]
