# Generated by Django 3.0.6 on 2020-08-17 13:04

from django.db import migrations, models


def make_many_customers(apps, schema_editor):
    UserSettings = apps.get_model("main", "UserSettings")

    for user in UserSettings.objects.all():
        user.customers.add(user.companyID)


class Migration(migrations.Migration):

    dependencies = [("main", "0021_auto_20200817_1833")]

    operations = [migrations.RunPython(make_many_customers)]
