# Generated by Django 3.0.6 on 2020-08-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0022_auto_20200817_1834")]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="customers",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="main.Company"
            ),
        )
    ]
