# Generated by Django 3.0.2 on 2020-08-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_theme'),
        ('main', '0023_auto_20200819_1015'),
    ]

    operations = [
    ]
