# Generated by Django 3.0.6 on 2020-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200819_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='last_pw_update_by',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_pw_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
