# Generated by Django 3.0.2 on 2020-09-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_merge_20200826_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='config',
            field=main.fields.SimpleJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
