# Generated by Django 3.0.6 on 2020-09-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200909_1713'),
        ('main', '0025_auto_20200901_1503'),
    ]

    operations = [
    ]
