# Generated by Django 3.0.6 on 2020-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_merge_20200929_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'UpdateRecords',
            },
        ),
    ]
