# Generated by Django 3.0.2 on 2020-10-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201007_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmforumuserassessment',
            name='criterion',
        ),
        migrations.AddField(
            model_name='tmforumuserassessment',
            name='sub_dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment', to='main.TMForumSubDimension'),
        ),
        migrations.AlterField(
            model_name='tmforumassignedassessment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmforum_assessment', to='main.Company'),
        ),
    ]
