# Generated by Django 3.0.2 on 2020-11-03 12:26

from django.db import migrations, models
import django.db.models.deletion
import main.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201019_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', main.fields.SimpleJSONField(blank=True, null=True)),
                ('user_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to='main.CourseLicenseUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
