# Generated by Django 3.0.2 on 2020-11-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_userreport'),
        ('main', '0033_auto_20201102_0253'),
    ]

    operations = [
    ]
