# Generated by Django 3.0.2 on 2021-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_menuitem_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='human_readable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='lms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentlicense',
            name='count',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='courselicense',
            name='count',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='component',
            field=models.TextField(blank=True, null=True),
        ),
    ]
