# Generated by Django 3.0.2 on 2021-04-11 17:00

from django.db import migrations, models
import django.db.models.deletion
import main.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_apprenticeship_apprenticeshiplicense_apprenticeshiplicenseuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCIndexAssessment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('has_report', models.BooleanField(default=False, null=True)),
                ('sent', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'gcindex_assessment',
            },
        ),
        migrations.CreateModel(
            name='GCState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'gcstate',
            },
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sub_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GCIndexReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.BinaryField(null=True)),
                ('report_data', main.fields.SimpleJSONField(default=dict, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='main.GCIndexAssessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gcindexassessment',
            name='gcologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcindex_users', to='main.UserSettings'),
        ),
        migrations.AddField(
            model_name='gcindexassessment',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcindex', to='main.GCState'),
        ),
        migrations.AddField(
            model_name='gcindexassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcindex', to='main.UserSettings'),
        ),
    ]
