# Generated by Django 3.0.2 on 2021-05-31 02:41

from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_gcindexassessment_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprenticeshipDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_logo', models.TextField(null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='apprenticeship',
            name='image',
            field=models.ImageField(null=True, upload_to=main.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='apprenticeship',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='apprenticeship',
            name='duration',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='apprenticeship',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apprenticeshiplicenseuser',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apprentices', to='main.ApprenticeshipDetails'),
        ),
    ]
