# Generated by Django 3.0.2 on 2021-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210531_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
