# Generated by Django 3.0.2 on 2021-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_elearninstates'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearninstates',
            name='account_status',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='certification_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='certification_status',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='concat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='course_activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='course_assignment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='course_completion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='course_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='course_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='course_type',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='live_class_attended',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='lvc_sore',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='order_type',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='osl_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='program',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='project_result',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='project_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='self_learning_completion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='team',
            field=models.CharField(blank=True, default='NA', max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='elearninstates',
            name='test_score',
            field=models.FloatField(null=True),
        ),
    ]
