# Generated by Django 3.0.2 on 2021-02-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'LMS Type',
                'verbose_name_plural': 'LMS Types',
            },
        ),
    ]
